# Generated by Django 4.2.11 on 2026-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('free', 'Gratuită'), ('paid', 'Plătită'), ('demo', 'Demo')], default='free', max_length=10)),
                ('phone_masked', models.CharField(blank=True, max_length=20)),
                ('requester_name', models.CharField(blank=True, max_length=100)),
                ('dedicated_to_name', models.CharField(blank=True, max_length=200)),
                ('col', models.PositiveSmallIntegerField()),
                ('row', models.PositiveSmallIntegerField()),
                ('dedication_type', models.CharField(blank=True, choices=[('mort', 'Adormiți'), ('viu', 'Vii')], max_length=10)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('referer', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Lumânare aprinsă',
                'verbose_name_plural': 'Lumânări aprinse',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Vizită',
                'verbose_name_plural': 'Vizite',
                'ordering': ['-timestamp'],
            },
        ),
    ]
