# Generated by Django 4.2.11 on 2026-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nume intern pentru identificare', max_length=120)),
                ('placement', models.CharField(choices=[('top_mobile', 'Top pagină — Mobil (ex: 320×50)'), ('top_desktop', 'Top pagină — Desktop (ex: 728×90)'), ('strip_mobile', 'Bandă în grid — Mobil (ex: 320×50, 300×250)'), ('inline_desktop', 'Inline în grid — Desktop (ex: 300×250, 468×60)')], db_index=True, max_length=20)),
                ('image_url', models.URLField(help_text='URL-ul imaginii bannerului')),
                ('link_url', models.URLField(help_text='URL la care duce click-ul (include https://)')),
                ('width', models.PositiveIntegerField(help_text='Lățime în px (ex: 320)')),
                ('height', models.PositiveIntegerField(help_text='Înălțime în px (ex: 50)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannere',
                'ordering': ['-created_at'],
            },
        ),
    ]
