# Generated by Django 4.2.11 on 2026-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Încarcă o imagine (opțional dacă folosești URL)', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL extern al imaginii (opțional dacă încarci fișier)'),
        ),
    ]
