# Generated by Django 4.2.11 on 2026-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_image_alter_banner_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('top_mobile', 'Top pagină — Mobil (ex: 320×50)'), ('top_desktop', 'Top pagină — Desktop (ex: 728×90)'), ('strip_mobile', 'Bandă în grid — Mobil (ex: 320×50, 300×250)'), ('inline_desktop', 'Inline în grid — Desktop (ex: 300×250, 468×60)')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Bifat = slotul este vizibil pe site')),
            ],
            options={
                'verbose_name': 'Slot banner',
                'verbose_name_plural': 'Sloturi bannere',
                'ordering': ['placement'],
            },
        ),
    ]
