# Generated by Django 4.2.11 on 2026-04-14 15:03

import apps.candles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('dedicated_to_name', models.CharField(max_length=200)),
                ('dedication_type', models.CharField(choices=[('viu', 'Pentru vii'), ('mort', 'Pentru morți')], default='viu', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.candles.models.candle_photo_upload_path)),
                ('renewal_sms_sent', models.BooleanField(default=False)),
                ('price_lei', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Burning'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('lit_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row', 'col'],
            },
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('col', 'row'), name='unique_active_candle_per_slot'),
        ),
    ]
