# Generated by Django 4.2.11 on 2026-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='dedication_type',
            field=models.CharField(choices=[('viu', 'Pentru vii'), ('mort', 'Pentru adormiți')], default='viu', max_length=10),
        ),
    ]
